# Generated by Django 5.2.7 on 2025-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="imagem1",
            field=models.ImageField(blank=True, null=True, upload_to="medeia/"),
        ),
    ]
