# Generated by Django 5.2.7 on 2025-10-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_produtos_imagem1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chave_grupo",
                to="app.grupo",
            ),
        ),
    ]
