# Generated by Django 5.2.7 on 2025-10-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_produtos_grupo"),
        ("grupo", "0002_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chave_grupo",
                to="grupo.group",
            ),
        ),
    ]
