# Generated by Django 5.2.7 on 2025-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_produtos_grupo"),
        ("volare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="grupovolare",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="grupovolare",
                to="volare.grupovolare",
            ),
        ),
    ]
