# Generated by Django 5.2.7 on 2025-10-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
    ]
