# Generated by Django 5.2.7 on 2025-10-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupo", "0002_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
